<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_(2)_ProductTile__gtm-click</name>
   <tag></tag>
   <elementGuidId>bb14c970-2eda-4b8b-9ac5-43ffa7b4b5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ProductTile__gtm-click</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='sectionFilteredCollectionGrid']/div/div[2]/div/div/div[2]/div[2]/div[2]/div/a/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ac991bd1-2e88-4c92-9d0a-eab17943d81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ProductTile__gtm-click</value>
      <webElementGuid>eea8fc32-2a79-4483-92b6-8131827540c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pid</name>
      <type>Main</type>
      <value>050011528001</value>
      <webElementGuid>ea33fd27-efb5-4b7e-8736-8f4110687d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>6853996544051</value>
      <webElementGuid>04257723-e388-4a5a-9f08-d15b0c9cebdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product-id</name>
      <type>Main</type>
      <value>6853996544051</value>
      <webElementGuid>d51180ec-128d-489c-811a-2e5b046126c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Franny Taffeta Bow Mini Party Dress</value>
      <webElementGuid>11ab362f-ec5e-46b8-b480-209089af672f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionFilteredCollectionGrid&quot;)/div[@class=&quot;Section__container&quot;]/div[2]/div[@class=&quot;FilteredCollection&quot;]/div[@class=&quot;FilteredCollection_container&quot;]/div[@class=&quot;FilteredCollection__flex-container&quot;]/div[@class=&quot;FilteredCollection__results-container&quot;]/div[@class=&quot;ResultsContainer ResultsContainer--2-mobile-columns&quot;]/div[@class=&quot;ProductTile ProductTile--react&quot;]/a[@class=&quot;ProductTile__image&quot;]/div[@class=&quot;ProductTile__btn-quickviewWrapper&quot;]/div[@class=&quot;ProductTile__btn-quickview&quot;]/div[@class=&quot;ProductTile__gtm-click&quot;]</value>
      <webElementGuid>bb1a370d-6f89-47ca-8d52-a52cb0e37744</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='sectionFilteredCollectionGrid']/div/div[2]/div/div/div[2]/div[2]/div[2]/div/a/div/div/div</value>
      <webElementGuid>501d547c-1439-489b-8b9b-f61aaecfb7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div/div/div</value>
      <webElementGuid>7be264ce-4d34-46fc-911b-f4a6f24992f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
