<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_(2)_hover-image lazyloaded</name>
   <tag></tag>
   <elementGuidId>d8bf4efa-dac9-4cd1-b7f1-8948512f1005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.hover-image.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='sectionFilteredCollectionGrid']/div/div[2]/div/div/div[2]/div[2]/div[2]/div/a/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a9ec3da2-a728-4e07-abf1-538f74b5f5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover-image lazyloaded</value>
      <webElementGuid>6356c87c-fc6d-4ea8-a7ca-f1961073d11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Franny Taffeta Bow Mini Party Dress</value>
      <webElementGuid>ff5d6b08-b9b6-4376-8e73-47e248c43b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>a274a7b7-764e-4124-b7fe-5ece8d51f9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>750</value>
      <webElementGuid>5ff03233-7dbe-49d8-aa06-7dba1af30950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product-id</name>
      <type>Main</type>
      <value>6853996544051</value>
      <webElementGuid>19629414-bc1b-4a2b-900d-b7cb943a0e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product-title</name>
      <type>Main</type>
      <value>Franny Taffeta Bow Mini Party Dress</value>
      <webElementGuid>32c61b14-aaa3-4df9-a352-c3ef56360190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.shopify.com/s/files/1/0070/8853/7651/products/05001-1528_3_5f64122a-6203-4e99-8435-bfe8bbdf0f47_500x750_crop_center.jpg?v=1675269818</value>
      <webElementGuid>b5908b9b-646e-4b6b-998d-40879333e999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionFilteredCollectionGrid&quot;)/div[@class=&quot;Section__container&quot;]/div[2]/div[@class=&quot;FilteredCollection&quot;]/div[@class=&quot;FilteredCollection_container&quot;]/div[@class=&quot;FilteredCollection__flex-container&quot;]/div[@class=&quot;FilteredCollection__results-container&quot;]/div[@class=&quot;ResultsContainer ResultsContainer--2-mobile-columns&quot;]/div[@class=&quot;ProductTile ProductTile--react&quot;]/a[@class=&quot;ProductTile__image&quot;]/img[@class=&quot;hover-image lazyloaded&quot;]</value>
      <webElementGuid>6ba67db0-db11-4be3-bba7-555a6e8f300c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='sectionFilteredCollectionGrid']/div/div[2]/div/div/div[2]/div[2]/div[2]/div/a/img[2]</value>
      <webElementGuid>bc084e68-c4bb-404e-9a33-22d0a6af9cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Franny Taffeta Bow Mini Party Dress'])[2]</value>
      <webElementGuid>49c1b03b-05b4-4a6e-9fd0-c5251799d60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>847732aa-5223-4175-bae1-a17abd4bcb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Franny Taffeta Bow Mini Party Dress' and @src = 'https://cdn.shopify.com/s/files/1/0070/8853/7651/products/05001-1528_3_5f64122a-6203-4e99-8435-bfe8bbdf0f47_500x750_crop_center.jpg?v=1675269818']</value>
      <webElementGuid>1256edbe-a89d-44f1-b63c-a4638b642c84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
