<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Details</name>
   <tag></tag>
   <elementGuidId>d0ad0f94-f3ef-4a95-9508-54d281f409aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ProductInfo__view-details.Button.Button--secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'View Details')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>834903cf-d189-488f-af63-67faee32e1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/lola-high-slit-satin-dress-050020505903</value>
      <webElementGuid>319fed38-da10-45fe-acee-165efac4c819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Lola</value>
      <webElementGuid>f3d4df7b-d86e-4d10-a8e6-2f10e6534c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>4648589033525</value>
      <webElementGuid>152d3c29-3ee3-465e-a936-e91c66f18fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ProductInfo__view-details Button Button--secondary</value>
      <webElementGuid>0a539976-611e-433d-a67b-31a20c55b0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>a1a3061d-5cb2-4c13-ab4e-f149de0b09c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QuickView&quot;)/div[@class=&quot;Modal__content&quot;]/div[@class=&quot;QuickView__content&quot;]/div[@class=&quot;ProductGrid&quot;]/div[@class=&quot;ProductInfo&quot;]/a[@class=&quot;ProductInfo__view-details Button Button--secondary&quot;]</value>
      <webElementGuid>598e9bfd-5ebb-4c52-a6b4-07fb181d6798</webElementGuid>
   </webElementProperties>
</WebElementEntity>
