<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Decline Offer</name>
   <tag></tag>
   <elementGuidId>b50c78db-d9c0-430d-b93f-a10d4c5f4ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bx-element-2012171-rN0VghG > button.bx-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='reset']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>38c8e5b0-9caf-47c4-981a-8253ff09f9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>reset</value>
      <webElementGuid>d37106c2-5169-4ef2-badd-e1861de62014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bx-button</value>
      <webElementGuid>a13b7ced-3ad1-4a04-ab29-a7ec6a87dc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>cb75a265-1eb1-46bc-834f-3e549799f9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Decline Offer; close the dialog</value>
      <webElementGuid>45bfd829-4e42-497b-8dfe-98b97e0fd17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Decline Offer</value>
      <webElementGuid>280de6da-67d1-416d-ac96-8210e7bc674a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bx-element-2012171-rN0VghG&quot;)/button[@class=&quot;bx-button&quot;]</value>
      <webElementGuid>b4fa8371-b97b-4cbb-a15a-3ddbaff657c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='reset']</value>
      <webElementGuid>7b8f1b33-210f-4c5e-a1f0-2af1a9ab8638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bx-element-2012171-rN0VghG']/button</value>
      <webElementGuid>7afaaf3e-84ca-4277-8213-f4eab2fadce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save for later'])[1]/following::button[1]</value>
      <webElementGuid>32b14033-e475-45c8-bd86-5b10c0fec446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get 15% Off'])[1]/following::button[2]</value>
      <webElementGuid>71397b88-cd6f-4294-9430-4a8db7cd243b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close email sign up dialog'])[2]/preceding::button[1]</value>
      <webElementGuid>3ac69b6d-cf1f-4530-8291-244630c3b70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your phone number to unlock 15% off and sign up for texts'])[1]/preceding::button[4]</value>
      <webElementGuid>3d2c7210-c095-452c-8d92-eb0c1a903ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Decline Offer']/parent::*</value>
      <webElementGuid>1c1741c8-6119-43e5-9fb1-3f3513f446f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/button</value>
      <webElementGuid>c474cb68-7799-4355-85d0-d347816e79c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'reset' and (text() = 'Decline Offer' or . = 'Decline Offer')]</value>
      <webElementGuid>ce1cf896-4fc2-45ba-b745-3e6efcd6ba9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
