<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Best Seller_ProductTile__gtm-click</name>
   <tag></tag>
   <elementGuidId>8dd78aad-3a3d-4aa8-bcce-40cbc4f042dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ProductTile__gtm-click</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='SearchResults']/div[2]/div/div/div/div[2]/div[2]/div[2]/div/a/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e05b8780-8e80-4191-a0ed-272e891af34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ProductTile__gtm-click</value>
      <webElementGuid>c4e70ca8-5b02-40a8-a383-da542f1fac5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pid</name>
      <type>Main</type>
      <value>050020505903</value>
      <webElementGuid>4349e4fa-280b-43e0-b6dc-c5a4f4040755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>3713981939763</value>
      <webElementGuid>8c2d59f8-d5f6-4b76-a38d-3e09e1d0b8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product-id</name>
      <type>Main</type>
      <value>3713981939763</value>
      <webElementGuid>e97edf0c-4905-4c65-906d-0ce45630768c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Lola High Slit Satin Dress</value>
      <webElementGuid>5cbcb17a-9028-44a7-97fa-38e0469f9dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchResults&quot;)/div[@class=&quot;Section__container&quot;]/div[@class=&quot;initialized&quot;]/div[@class=&quot;FilteredCollection&quot;]/div[@class=&quot;FilteredCollection_container&quot;]/div[@class=&quot;FilteredCollection__flex-container&quot;]/div[@class=&quot;FilteredCollection__results-container&quot;]/div[@class=&quot;ResultsContainer ResultsContainer--2-mobile-columns&quot;]/div[@class=&quot;ProductTile ProductTile--react&quot;]/a[@class=&quot;ProductTile__image&quot;]/div[@class=&quot;ProductTile__btn-quickviewWrapper&quot;]/div[@class=&quot;ProductTile__btn-quickview&quot;]/div[@class=&quot;ProductTile__gtm-click&quot;]</value>
      <webElementGuid>0fad6c55-5c76-4580-8266-20d05907970f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='SearchResults']/div[2]/div/div/div/div[2]/div[2]/div[2]/div/a/div[2]/div/div</value>
      <webElementGuid>0e50c30e-0c02-40af-99e6-4e52622b2b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div/div</value>
      <webElementGuid>1192b5d1-368a-4c26-9d45-c8d82180cbfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
