<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_(1)_hover-image lazyloaded</name>
   <tag></tag>
   <elementGuidId>5cf4863c-9976-4a11-a0d4-e4977569c1ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.hover-image.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='SearchResults']/div[2]/div/div/div/div[2]/div[2]/div[2]/div/a/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9827093d-0fc7-49ff-bde3-556cbe3335b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover-image lazyloaded</value>
      <webElementGuid>1b527bc7-82bc-4eaf-a39f-417d105c24be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lola High Slit Satin Dress</value>
      <webElementGuid>be5a0e19-bc7e-49dc-801f-ae60b201a155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>652ce690-3d56-445e-b249-68e3f45c655d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>750</value>
      <webElementGuid>c1a2da27-0f46-43bc-a7ef-26cf1fd2dea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product-id</name>
      <type>Main</type>
      <value>3713981939763</value>
      <webElementGuid>cbb04730-7d4f-4250-9856-253bd91cf7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product-title</name>
      <type>Main</type>
      <value>Lola High Slit Satin Dress</value>
      <webElementGuid>e9c85e9c-98c4-45b6-8d2a-0fbe2c3624a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.shopify.com/s/files/1/0070/8853/7651/products/05002-1118_2_500x750_crop_center.jpg?v=1675360974</value>
      <webElementGuid>261f5d10-d26e-4e50-b37f-ac447c4b6116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchResults&quot;)/div[@class=&quot;Section__container&quot;]/div[@class=&quot;initialized&quot;]/div[@class=&quot;FilteredCollection&quot;]/div[@class=&quot;FilteredCollection_container&quot;]/div[@class=&quot;FilteredCollection__flex-container&quot;]/div[@class=&quot;FilteredCollection__results-container&quot;]/div[@class=&quot;ResultsContainer ResultsContainer--2-mobile-columns&quot;]/div[@class=&quot;ProductTile ProductTile--react&quot;]/a[@class=&quot;ProductTile__image&quot;]/img[@class=&quot;hover-image lazyloaded&quot;]</value>
      <webElementGuid>8365d581-bb77-4cbc-a502-4d31ad214016</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='SearchResults']/div[2]/div/div/div/div[2]/div[2]/div[2]/div/a/img[2]</value>
      <webElementGuid>8fbf7e1d-746f-42e8-b894-174c2545db16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Lola High Slit Satin Dress'])[2]</value>
      <webElementGuid>eb07f4d8-01a6-4948-9f42-8b3eeb54ccbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>a3d96c22-947b-4305-9f9e-03d7e6f0d094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Lola High Slit Satin Dress' and @src = 'https://cdn.shopify.com/s/files/1/0070/8853/7651/products/05002-1118_2_500x750_crop_center.jpg?v=1675360974']</value>
      <webElementGuid>4e856f76-da56-416b-a993-6b302eef3459</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
