<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_zipcodestores</name>
   <tag></tag>
   <elementGuidId>561da920-d2e2-490f-bb00-470bccee7d06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/main[@id='MainContent']/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/input[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
