<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_milesdropdown</name>
   <tag></tag>
   <elementGuidId>8cba7292-82b9-4260-a51d-e3f0b8831145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/main[@id='MainContent']/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/select[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
