<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Free Shipping Over AUD130</name>
   <tag></tag>
   <elementGuidId>b1a152ba-613a-4993-80ba-de35a774d301</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#INF-Header-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='INF-Header-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>12476762-6df0-4a1d-b9b2-72973fe3d3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>INF-Header-4</value>
      <webElementGuid>038732ce-fabe-4d85-aff9-cf535816fe7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gtm--item-track</value>
      <webElementGuid>8dec8240-6be0-4376-849c-05366e59b79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-id</name>
      <type>Main</type>
      <value>INF-Header-4</value>
      <webElementGuid>eb99bd04-6320-4c18-80c3-18015b742a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promo-type</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>fc6bf8a2-cb46-4535-8150-03479ea9dfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promo-creative</name>
      <type>Main</type>
      <value>International Announcement Bar</value>
      <webElementGuid>e5410152-7736-45bc-a6ce-4c39ab57822e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/best-selling-dresses</value>
      <webElementGuid>d8b69500-e523-4f04-aa84-54ac6ca6a92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-first-on-screen-11638715_334</name>
      <type>Main</type>
      <value>1201</value>
      <webElementGuid>f9952e22-7f63-4e16-9382-c7e23d700ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-total-visible-time-11638715_334</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>891d26c2-f126-4a06-a8e3-46882469a08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-has-fired-11638715_334</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9ee8c31a-cbc6-40a7-9124-fffcf69789f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-section-tracking</name>
      <type>Main</type>
      <value>vp2-cr2-m1-txt2</value>
      <webElementGuid>c025ea41-a42b-48c3-8335-e9ece7f80494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Free Shipping Over AUD$130</value>
      <webElementGuid>36cdfd6e-c4d6-45ea-a345-fb2cebb32e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;INF-Header-4&quot;)</value>
      <webElementGuid>5a6fd226-a3fa-4ba2-8726-0beb86ec771a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='INF-Header-4']</value>
      <webElementGuid>b5951d0f-2b7f-48b9-9701-4797ea538605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PreHeader__announcements']/section[2]/div/div/div[2]/span/a</value>
      <webElementGuid>9cde5331-5a1b-4eec-ac1e-b3f491ad954f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Free Shipping Over AUD$130')]</value>
      <webElementGuid>16475753-9708-41de-8570-16e4d6fe7d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Big | 60% Off Sale Styles!'])[3]/following::a[1]</value>
      <webElementGuid>c781a704-702d-4c82-9ad8-cadb80b2375a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Pay | Check Out Faster!'])[2]/following::a[2]</value>
      <webElementGuid>ca1735e3-014f-47aa-a428-115ddd4184c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[1]/preceding::a[1]</value>
      <webElementGuid>2c98dacd-36d2-447d-8f57-af97cafd5901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[2]/preceding::a[1]</value>
      <webElementGuid>989669f1-b0a2-4b8b-9c7e-63ebbfd871cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/collections/best-selling-dresses')])[3]</value>
      <webElementGuid>90427156-f872-4f33-80f7-adb92c035987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div[2]/span/a</value>
      <webElementGuid>d0f91b81-3756-406d-aa53-244582b3bd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'INF-Header-4' and @href = '/collections/best-selling-dresses' and (text() = 'Free Shipping Over AUD$130' or . = 'Free Shipping Over AUD$130')]</value>
      <webElementGuid>26f07d36-a162-4519-b741-3ba996876780</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
