<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Floral</name>
   <tag></tag>
   <elementGuidId>6b729e6e-e1a5-4630-b459-5432608431e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-INF-Header']/div/div/header/div/div/nav/ul/li/div/ul/li[2]/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8537aa1f-f520-436d-a75e-81f541fc580a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
                        HeaderNav__link
                        
                      </value>
      <webElementGuid>ae08d243-b9d4-472a-8755-f48646a6ed14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/featured-floral</value>
      <webElementGuid>08a621b2-ddc7-48a3-9d8d-8b1a253ae3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-category</name>
      <type>Main</type>
      <value>NEW &amp; NOW</value>
      <webElementGuid>6b14e65c-a8e6-4680-b04f-8d99b707fff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sub-category</name>
      <type>Main</type>
      <value>Floral</value>
      <webElementGuid>557d202b-0bb8-4176-b295-79cdcb158a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Floral</value>
      <webElementGuid>c88fdd64-6558-42b7-87aa-b90d61211ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-INF-Header&quot;)/div[@class=&quot;Headroom--disabled Headroom--disabled-mobile&quot;]/div[@class=&quot;Header Header--has-preheader Header--has-preheader-mobile Header--buttons-placement-main&quot;]/header[@class=&quot;Header__desktop Section Section--fixed Section--side-gutters&quot;]/div[@class=&quot;Section__container&quot;]/div[@class=&quot;NavBar 
      
      NavBar--has-preheader&quot;]/nav[@class=&quot;NavBar__primary NavBar__primary--center&quot;]/ul[@class=&quot;HeaderNav&quot;]/li[@class=&quot;HeaderNav__heading&quot;]/div[@class=&quot;HeaderNav__menu&quot;]/ul[@class=&quot;HeaderNav__menu-grid&quot;]/li[@class=&quot;HeaderNav__menu-column HeaderNav__menu-column--1&quot;]/ul[@class=&quot;HeaderNav__link-items&quot;]/li[@class=&quot;HeaderNav__link-item&quot;]/a[@class=&quot;HeaderNav__link&quot;]</value>
      <webElementGuid>ac3a4706-94a4-43d1-a38e-ccf46d0653c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-INF-Header']/div/div/header/div/div/nav/ul/li/div/ul/li[2]/ul/li[5]/a</value>
      <webElementGuid>747514f1-00db-401e-9bed-32c6b66e806d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Floral')]</value>
      <webElementGuid>82bcfd83-7e37-47ff-9938-4d0d2dc9b2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summer Whites'])[1]/following::a[1]</value>
      <webElementGuid>94690a26-41e6-43d1-a87a-38463c287a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summer'])[1]/following::a[2]</value>
      <webElementGuid>87fd76dd-04d5-4904-800f-45ddda0d4cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ruffles'])[1]/preceding::a[1]</value>
      <webElementGuid>92ab8d30-0fc3-4746-b938-57b63c31c429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ruched'])[1]/preceding::a[2]</value>
      <webElementGuid>9d08367e-1d62-4873-867f-70f1fd248465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Floral']/parent::*</value>
      <webElementGuid>e9ec984b-6caa-494e-98a4-94bd1f56c5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/collections/featured-floral')]</value>
      <webElementGuid>a8a79b46-4b5a-46ce-b341-badb02706e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[5]/a</value>
      <webElementGuid>a6342296-4018-4839-9421-daf117f4a971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/featured-floral' and (text() = 'Floral' or . = 'Floral')]</value>
      <webElementGuid>a69b145f-41c8-4620-a11d-b8300da2ab82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
