<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SHOP NOW</name>
   <tag></tag>
   <elementGuidId>4c084ae9-4879-44fc-a258-e2d65103538e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1645218134fec9e555-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'SHOP NOW')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe893d0c-a63b-4751-83fe-83a15bb6e027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1645218134fec9e555-1</value>
      <webElementGuid>f0d824f2-7846-4e29-8cf4-089745b05132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-id</name>
      <type>Main</type>
      <value>1645218134fec9e555-1</value>
      <webElementGuid>2740c565-bab4-480d-881d-0012dc0b8423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promo-type</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>4ae37a73-a024-4c15-b3b1-f1be1e6600e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promo-creative</name>
      <type>Main</type>
      <value>Hero Banner - Special Occasion Dresses</value>
      <webElementGuid>09139e38-7917-4ac9-8c2b-dd4fcedc15f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>SHOP NOW</value>
      <webElementGuid>5803aade-7c96-4c24-93ef-0cbe16cb1227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>HeroBanner__button gtm--item-track Button Button--secondary</value>
      <webElementGuid>7cc10636-10e7-4e56-8e93-ba810d11b2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections</value>
      <webElementGuid>68f5360d-8be9-4af6-a329-9b31b26fbf65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-section-tracking</name>
      <type>Main</type>
      <value>vp3-hero1-m1-btn1</value>
      <webElementGuid>194de4ca-4e41-4aee-b7a1-a634652cf666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-recent-on-screen-58102283_300</name>
      <type>Main</type>
      <value>484</value>
      <webElementGuid>42691e20-6329-4fe5-bf17-7b83a6547024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-first-on-screen-58102283_300</name>
      <type>Main</type>
      <value>484</value>
      <webElementGuid>7976168b-6495-4043-96f9-a5e63f183bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-total-visible-time-58102283_300</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>3f6873c5-4b04-40a0-b61f-7ea9f46b3026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-has-fired-58102283_300</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1268a425-7781-4315-9e01-5fe7191fe52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-recent-on-screen-58102283_370</name>
      <type>Main</type>
      <value>487</value>
      <webElementGuid>4e822a2d-e540-4c80-8b28-4273af96666b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-first-on-screen-58102283_370</name>
      <type>Main</type>
      <value>487</value>
      <webElementGuid>58843aa4-a90e-4f36-bdee-92f1b97a3178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-total-visible-time-58102283_370</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>24c2efb7-0290-442f-bf40-c5074a11b311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-has-fired-58102283_370</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0c1f2117-5ad8-48af-aa76-1f5d30b170a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    SHOP NOW
                  </value>
      <webElementGuid>1d4da8af-12e7-48fd-813f-da670f6254e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Overlay-1645218134fec9e555-0&quot;)/div[@class=&quot;HeroBanner__buttons&quot;]/a[@id=&quot;1645218134fec9e555-1&quot;]</value>
      <webElementGuid>7c53b4c8-90b0-4344-8b8a-91b69f4f1293</webElementGuid>
   </webElementProperties>
</WebElementEntity>
