<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Go_ispbxii_1</name>
   <tag></tag>
   <elementGuidId>9352aa79-108b-4dac-a2b9-576b6d2272b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ispbxii_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ispbxii_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e65f43e-3535-4467-bb49-d5fdd0f6b0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchForm__mobile-input isp_ignore</value>
      <webElementGuid>53188bc9-7374-40ae-8b57-96b0eeed0449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb5bb5b6-0b02-4a41-9e4a-d28ec0f92795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>d0093cdc-405d-4b26-bddc-d6916c934fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a03999b1-15b0-429c-a9cb-650414bce353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0d886e7c-d2eb-4979-8f61-cd7cd63c6c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3470502a-7a4e-4d05-b7ae-c6a3d6b7c439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ispbxii_1</value>
      <webElementGuid>95c8f9de-3c25-4516-9844-b2de3da4e6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ispbxii_1&quot;)</value>
      <webElementGuid>937c9d1c-fab0-40b0-b633-f380f66f65d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ispbxii_1']</value>
      <webElementGuid>97b9f2f8-78b7-4a61-9ea1-dd06bcc00db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-INF-Header']/div/div/div[2]/div/div/div/form/input</value>
      <webElementGuid>3608ff9a-b214-47c7-85f0-1133d011f0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/form/input</value>
      <webElementGuid>f6433c93-cae7-4e69-9229-da71828750af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'search' and @id = 'ispbxii_1']</value>
      <webElementGuid>8e34146f-cffa-4c82-8c7d-565e7efb8ac3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
