<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lola_satin_dress_defaultimage</name>
   <tag></tag>
   <elementGuidId>9a8fa02d-9e6e-4d57-a823-2ce5b2414d3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/main[@id='MainContent']/section[@id='SearchResults']/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/a[1]/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
