<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Go</name>
   <tag></tag>
   <elementGuidId>6ab7e035-0616-4d2e-880a-a98d2c5be3d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Section__container > div > div.SearchBar > form.SearchForm > button.SearchForm__mobile-go > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-INF-Header']/div/div/div[2]/div/div/div/form/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d0f400a6-3182-441d-8e76-81a6aa4ae371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>a4b066af-3b12-4ba6-96fe-e25ed80e0acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-INF-Header&quot;)/div[@class=&quot;Headroom--disabled Headroom--disabled-mobile&quot;]/div[@class=&quot;Header Header--has-preheader Header--has-preheader-mobile Header--buttons-placement-main&quot;]/div[@class=&quot;SearchDrawer Section Section--full Section--relative SearchDrawer--open&quot;]/div[@class=&quot;Section__container&quot;]/div[1]/div[@class=&quot;SearchBar&quot;]/form[@class=&quot;SearchForm&quot;]/button[@class=&quot;SearchForm__mobile-go&quot;]/span[1]</value>
      <webElementGuid>d6acfa23-785f-4aa1-9363-6b8cf905dbbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-INF-Header']/div/div/div[2]/div/div/div/form/button/span</value>
      <webElementGuid>e21d9200-2669-4b81-b41c-2eeab3a7bc51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/following::span[17]</value>
      <webElementGuid>3641b9e4-4936-4581-b378-6f0aa6c1d366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shoes On Sale'])[1]/following::span[18]</value>
      <webElementGuid>d4102ad5-5651-4903-9a7b-c1626e081f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support'])[1]/preceding::span[1]</value>
      <webElementGuid>f6fb82ca-2172-4704-bbdd-19d13b434a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find a Store'])[1]/preceding::span[1]</value>
      <webElementGuid>388d05c9-ea5e-43a0-96ab-0b83e4839d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/form/button/span</value>
      <webElementGuid>1570f095-6b7c-4490-98bc-6df8df9a77bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Go' or . = 'Go')]</value>
      <webElementGuid>e6aec78e-30a1-465d-b8c9-715ebeac83b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
