<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>83e0697a-53fd-41a6-9698-797d1c15abcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.MobileLogo__image > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header/div[1]/div[1]/div[1]/h1[1]/a[1]/*[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>e2ab38da-363c-469a-b0a1-68ebbd3dce2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>8f511f46-1c6a-4fd6-af1b-c617ba73f8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>e82bb5ac-97bc-4627-875a-c49cfbc16d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:xlink</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xlink</value>
      <webElementGuid>e308ee5f-588e-4187-8690-edb4cb41104b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>2eefc852-cff4-4677-8abf-7ef8835a0526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>dca623c0-53e6-4c08-8f5d-715a58ebcc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 612 130.8</value>
      <webElementGuid>74428091-7c6b-4daa-85d6-85d2a4955d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enable-background</name>
      <type>Main</type>
      <value>new 0 0 612 130.8</value>
      <webElementGuid>e8bb9a9b-6ad0-460f-9ee9-a2929ef843fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xml:space</name>
      <type>Main</type>
      <value>preserve</value>
      <webElementGuid>1809e944-3051-44b0-a2bb-3bc61c4c0bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-INF-Header&quot;)/div[@class=&quot;Headroom--disabled Headroom--disabled-mobile&quot;]/div[@class=&quot;Header Header--has-preheader Header--has-preheader-mobile Header--buttons-placement-main&quot;]/header[@class=&quot;Header__mobile&quot;]/div[@class=&quot;MobileBar&quot;]/div[@class=&quot;MobileLogo&quot;]/a[@class=&quot;MobileLogo__image&quot;]/svg[1]</value>
      <webElementGuid>640b0a8e-e2c6-4ccd-b6a3-060476185c3a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
