<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mobile_plp_sort_featured</name>
   <tag></tag>
   <elementGuidId>f7cc6e4b-6bdc-4c9b-ab83-80eb4d37bc83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='FiltersContainer__mobile-controls']//select[@class='SortSelection__select']//option[contains(text(),'Featured')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
