<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mobile_submenu_for_the_bride</name>
   <tag></tag>
   <elementGuidId>f127a155-08fd-4398-995d-56e70138031f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;shopify-section-INF-Header&quot;]/div[2]/div/div[1]/div/div[8]/div[7]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
