<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mobile_homepage_currency_ship</name>
   <tag></tag>
   <elementGuidId>e8294fdc-6356-4173-9052-860862a2752e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.ProductTile__price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ae-unique-id-0&quot;]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
