<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mobile_cart_verify_correct_price</name>
   <tag></tag>
   <elementGuidId>f8fe81b3-d902-41fc-8d90-042af7ddbc49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;cart_form&quot;]/div/div/div/div[2]/div[1]/div[2]/div[2]/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
