<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Floral</name>
   <tag></tag>
   <elementGuidId>70bb62a2-46e2-4e43-87d8-dcad7bc50ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.CollectionHeader__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='MainContent']/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>93db2100-9ed4-405e-8efd-280fa460e281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-collection-title</name>
      <type>Main</type>
      <value>Floral</value>
      <webElementGuid>07c6c87b-6611-4303-a15b-9a5ef5717214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CollectionHeader__title</value>
      <webElementGuid>4d07e862-6593-4bb7-afce-a6ff101983b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Floral</value>
      <webElementGuid>51c2ca93-eb3b-4775-a303-26567ef828ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent&quot;)/div[@class=&quot;CollectionHeaderComponent CollectionHeader__hide&quot;]/div[@class=&quot;CollectionHeader__container has-background&quot;]/h1[@class=&quot;CollectionHeader__title&quot;]</value>
      <webElementGuid>70223dbf-6b69-4755-9636-f60d2b8d6707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='MainContent']/div/div/h1</value>
      <webElementGuid>114b254d-2000-4aee-9708-43f4ba572456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Now'])[1]/following::h1[1]</value>
      <webElementGuid>5a39033d-eb3e-45ef-99d7-8d82980b3b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Added to Wishlist'])[1]/following::h1[1]</value>
      <webElementGuid>1cb86d99-c99b-44cf-b6b0-63769a0be343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::h1[1]</value>
      <webElementGuid>09701764-dc91-4b99-992f-873478c0dc00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::h1[1]</value>
      <webElementGuid>db49053d-b17c-4541-a24c-4aabfa7e89c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>f7311dfe-c7f0-4c91-9594-2bc6cbb5bfc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Floral' or . = 'Floral')]</value>
      <webElementGuid>b6aebe86-6cd1-4e44-ab82-cd391a5043c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
