<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_Sale</name>
   <tag></tag>
   <elementGuidId>e3a0b843-d47b-4e7b-be42-e85ccdbc01c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;shopify-section-INF-Header&quot;]/div[1]/div[1]/header[1]/div/div/nav/ul/li[9]/a/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
