<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>homepage_logo</name>
   <tag></tag>
   <elementGuidId>4667c9da-7319-471d-bcf4-159a25a01cee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='NavBar__logo-image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
