<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_text_verification</name>
   <tag></tag>
   <elementGuidId>97d7e4cc-41e9-4edc-ad56-8afac0290270</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/main[@id='MainContent']/section[@id='SearchResults']/div[1]/h1[1]/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
