<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>country_US</name>
   <tag></tag>
   <elementGuidId>80f6cf19-6383-41c1-91b9-1a8f11a96682</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='shopify-section-INF-Header']/div[1]/div[3]/div[1]/div[1]/div[1]/form[1]/div[1]/ul[1]/li[205]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
