<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>country_other</name>
   <tag></tag>
   <elementGuidId>d1209f23-5521-41b1-b0d9-6b46677e1672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='shopify-section-INF-Header']/div[1]/div[3]/div[1]/div[1]/div[1]/form[1]/div[1]/ul[1]/li[204]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
